#include<iostream>
/*
* automaticlly generated by my notion AI...
*/

/*
* Singleton design pattern is used when only one object is required to coordinate actions across the system.
* This is useful when we need to make sure that only one instance of a class is created and used throughout the program.
*
* The constructor of Singleton class will be private so that instantiate object from outside is impossible.
* The unique object is created in the scope of GetInstance() function.
*
* Please note that Singleton is not thread-safe.
* To make it thread-safe, use Double-Check Locking method or C++11's std::once_flag.
*/

class Singleton
{
private:
    Singleton() = default;
    static Singleton* s_instance;
public:
    static Singleton* GetInstance()
    {
        if (s_instance == nullptr)
        {
            s_instance = new Singleton();
            std::cout << "New Singleton object created." << std::endl;
        }
        else
        {
            std::cout << "Returning existing Singleton object." << std::endl;
        }

        return s_instance;
    }

    void Hello() {}
};

Singleton* Singleton::s_instance = nullptr;

int main()
{
    Singleton* s1 = Singleton::GetInstance();
    Singleton* s2 = Singleton::GetInstance();
    Singleton::GetInstance()->Hello;

    if (s1 == s2)
    {
        std::cout << "Both pointers point to the same object." << std::endl;
    }
    else
    {
        std::cout << "Both pointers point to different objects." << std::endl;
    }
}