; Listing generated by Microsoft (R) Optimizing Compiler Version 19.35.32216.1 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

msvcjmc	SEGMENT
__7424102C_concurrencysal@h DB 01H
__7D4DA4FA_sal@h DB 01H
__0FC31696_vadefs@h DB 01H
__B56ADB44_vcruntime@h DB 01H
__51B79E59_xkeycheck@h DB 01H
__B5DFE31F_yvals_core@h DB 01H
__C9B856CF_limits@h DB 01H
__2674127B_climits DB 01H
__04C75F1C_corecrt@h DB 01H
__EBA563F3_vcruntime_new@h DB 01H
__D7109CAF_vcruntime_new_debug@h DB 01H
__8CF369C8_crtdbg@h DB 01H
__00CBEA8D_crtdefs@h DB 01H
__8FC982FD_use_ansi@h DB 01H
__14DB8636_yvals@h DB 01H
__92857972_corecrt_math@h DB 01H
__A29DED85_math@h DB 01H
__494656A0_corecrt_malloc@h DB 01H
__0C5B3DCC_stddef@h DB 01H
__F1F53BCE_corecrt_search@h DB 01H
__DD5AA43A_corecrt_wstdlib@h DB 01H
__71F46169_stdlib@h DB 01H
__A29B3089_cstdlib DB 01H
__74C7B0B4_xtr1common DB 01H
__25BDFE26_intrin0@inl@h DB 01H
__19E65386_intrin0@h DB 01H
__1FF7AA4D_cmath DB 01H
__C44F8F6B_corecrt_stdio_config@h DB 01H
__A7F89B2B_corecrt_wstdio@h DB 01H
__B5C48800_stdio@h DB 01H
__6855AA31_cstdio DB 01H
__15E49872_errno@h DB 01H
__E37A6634_vcruntime_string@h DB 01H
__184F7456_corecrt_memcpy_s@h DB 01H
__82377222_corecrt_memory@h DB 01H
__5B29309E_corecrt_wstring@h DB 01H
__F787F5CD_string@h DB 01H
__EE099869_cstring DB 01H
__E387ED1C_corecrt_wconio@h DB 01H
__78D0C915_corecrt_wctype@h DB 01H
__02A4DD57_corecrt_wdirect@h DB 01H
__A056EFF3_corecrt_share@h DB 01H
__91FC0EDF_corecrt_wio@h DB 01H
__6619318A_corecrt_wprocess@h DB 01H
__18070508_corecrt_wtime@h DB 01H
__3D2AFB26_types@h DB 01H
__72103B05_stat@h DB 01H
__4BE26BFD_wchar@h DB 01H
__F2DE7C62_cwchar DB 01H
__0750EA24_cstddef DB 01H
__6EE2661F_initializer_list DB 01H
__62892210_xstddef DB 01H
__B11EF954_iosfwd DB 01H
__77CE78F0_stdint@h DB 01H
__1FC5D1F4_cstdint DB 01H
__1F1E5892_type_traits DB 01H
__9596B502_utility DB 01H
__9E977780___msvc_iter_core@hpp DB 01H
__1B16000D_xutility DB 01H
__0ABAB74D_iterator DB 01H
__83BF90D8_share@h DB 01H
__4E75CBD7___msvc_system_error_abi@hpp DB 01H
__F574DECA_cerrno DB 01H
__E5D9469F_malloc@h DB 01H
__C78E68C1_corecrt_terminate@h DB 01H
__6D69B109_eh@h DB 01H
__DFFE99FD_vcruntime_exception@h DB 01H
__C894841B_exception DB 01H
__CDB0EEF0_float@h DB 01H
__1B1161B6_cfloat DB 01H
__30F16C47_isa_availability@h DB 01H
__7DF72CD2_limits DB 01H
__1F199A81_new DB 01H
__C29808CD_xatomic@h DB 01H
__FF03D6C1_xmemory DB 01H
__8BD0505D_xstring DB 01H
__41DABE46_stdexcept DB 01H
__F6473D4F_xcall_once@h DB 01H
__BC4E9339_xerrc@h DB 01H
__93FD7E51_time@h DB 01H
__D9443645_ctime DB 01H
__ADD2E34C_xtimec@h DB 01H
__EE87B54E_xthreads@h DB 01H
__16C27010_atomic DB 01H
__491A2F6F_system_error DB 01H
__8A79911F_vcruntime_typeinfo@h DB 01H
__6BC9F314_typeinfo DB 01H
__C159205C_memory DB 01H
__ED1C7753_xfacet DB 01H
__393F9422___msvc_xlocinfo_types@hpp DB 01H
__6AECDA3E_ctype@h DB 01H
__679E4D96_cctype DB 01H
__66B29864_locale@h DB 01H
__3137EC58_clocale DB 01H
__744010DC_xlocinfo DB 01H
__54EE246C_xlocale DB 01H
__4DA567CF_xiosbase DB 01H
__437A06FA_streambuf DB 01H
__CA69427B_xlocnum DB 01H
__E7D4A097_ios DB 01H
__47FEFEA8_ostream DB 01H
__242ECB92_istream DB 01H
__796F7A12_iostream DB 01H
__B58AA6C0_string DB 01H
__201522C9_Main@cpp DB 01H
msvcjmc	ENDS
PUBLIC	?__empty_global_delete@@YAXPEAX@Z		; __empty_global_delete
PUBLIC	?__empty_global_delete@@YAXPEAX_K@Z		; __empty_global_delete
PUBLIC	??0Vector3@@QEAA@XZ				; Vector3::Vector3
PUBLIC	main
PUBLIC	__JustMyCode_Default
EXTRN	??2@YAPEAX_K@Z:PROC				; operator new
EXTRN	??3@YAXPEAX_K@Z:PROC				; operator delete
EXTRN	??_U@YAPEAX_K@Z:PROC				; operator new[]
EXTRN	??_V@YAXPEAX@Z:PROC				; operator delete[]
EXTRN	__imp_?get@?$basic_istream@DU?$char_traits@D@std@@@std@@QEAAHXZ:PROC
EXTRN	_RTC_CheckStackVars:PROC
EXTRN	_RTC_InitBase:PROC
EXTRN	_RTC_Shutdown:PROC
EXTRN	__CheckForDebuggerJustMyCode:PROC
EXTRN	__GSHandlerCheck_EH4:PROC
EXTRN	__security_check_cookie:PROC
EXTRN	__imp_?cin@std@@3V?$basic_istream@DU?$char_traits@D@std@@@1@A:BYTE
EXTRN	__security_cookie:QWORD
;	COMDAT pdata
pdata	SEGMENT
$pdata$?__empty_global_delete@@YAXPEAX@Z DD imagerel $LN3
	DD	imagerel $LN3+41
	DD	imagerel $unwind$?__empty_global_delete@@YAXPEAX@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?__empty_global_delete@@YAXPEAX_K@Z DD imagerel $LN3
	DD	imagerel $LN3+46
	DD	imagerel $unwind$?__empty_global_delete@@YAXPEAX_K@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??0Vector3@@QEAA@XZ DD imagerel $LN3
	DD	imagerel $LN3+89
	DD	imagerel $unwind$??0Vector3@@QEAA@XZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$main DD	imagerel $LN12
	DD	imagerel $LN12+731
	DD	imagerel $unwind$main
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$main$dtor$0 DD imagerel main$dtor$0
	DD	imagerel main$dtor$0+44
	DD	imagerel $unwind$main$dtor$0
pdata	ENDS
;	COMDAT rtc$TMZ
rtc$TMZ	SEGMENT
_RTC_Shutdown.rtc$TMZ DQ FLAT:_RTC_Shutdown
rtc$TMZ	ENDS
;	COMDAT rtc$IMZ
rtc$IMZ	SEGMENT
_RTC_InitBase.rtc$IMZ DQ FLAT:_RTC_InitBase
rtc$IMZ	ENDS
;	COMDAT voltbl
voltbl	SEGMENT
_volmd	DB	00H
	DB	05H
voltbl	ENDS
;	COMDAT voltbl
voltbl	SEGMENT
_volmd	DW	02aH
	DW	02c2H
voltbl	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$main$dtor$0 DD 031001H
	DD	0700c4210H
	DD	0500bH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$ip2state$main DB 06H
	DB	00H
	DB	00H
	DB	0c5H, 05H
	DB	02H
	DB	'p'
	DB	00H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$stateUnwindMap$main DB 02H
	DB	0eH
	DD	imagerel main$dtor$0
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$cppxdata$main DB 028H
	DD	imagerel $stateUnwindMap$main
	DD	imagerel $ip2state$main
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$main DD	025053119H
	DD	010a230fH
	DD	070030057H
	DD	05002H
	DD	imagerel __GSHandlerCheck_EH4
	DD	imagerel $cppxdata$main
	DD	02a2H
xdata	ENDS
;	COMDAT CONST
CONST	SEGMENT
main$rtcName$0 DB 061H
	DB	072H
	DB	072H
	DB	061H
	DB	079H
	DB	00H
	ORG $+2
main$rtcName$1 DB 076H
	DB	065H
	DB	063H
	DB	074H
	DB	06fH
	DB	072H
	DB	00H
	ORG $+1
main$rtcVarDesc DD 078H
	DD	0cH
	DQ	FLAT:main$rtcName$1
	DD	048H
	DD	014H
	DQ	FLAT:main$rtcName$0
	ORG $+96
main$rtcFrameData DD 02H
	DD	00H
	DQ	FLAT:main$rtcVarDesc
CONST	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??0Vector3@@QEAA@XZ DD 025051301H
	DD	010e2313H
	DD	07007001dH
	DD	05006H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?__empty_global_delete@@YAXPEAX_K@Z DD 025051801H
	DD	01132318H
	DD	0700c001dH
	DD	0500bH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?__empty_global_delete@@YAXPEAX@Z DD 025051301H
	DD	010e2313H
	DD	07007001dH
	DD	05006H
xdata	ENDS
; Function compile flags: /Odt
;	COMDAT __JustMyCode_Default
_TEXT	SEGMENT
__JustMyCode_Default PROC				; COMDAT
	ret	0
__JustMyCode_Default ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File C:\Users\binyi\source\repos\cpp_StackHeap\cpp_StackHeap\Main.cpp
;	COMDAT main
_TEXT	SEGMENT
value$ = 4
array$ = 40
vector$ = 88
hvalue$ = 136
harray$ = 168
hvector$ = 200
$T5 = 424
$T6 = 456
$T7 = 488
$T8 = 520
$T9 = 552
$T10 = 584
$T11 = 616
tv148 = 632
tv144 = 632
tv141 = 632
tv138 = 632
__$ArrayPad$ = 640
main	PROC						; COMDAT

; 12   : {

$LN12:
	push	rbp
	push	rdi
	sub	rsp, 696				; 000002b8H
	lea	rbp, QWORD PTR [rsp+32]
	lea	rdi, QWORD PTR [rsp+32]
	mov	ecx, 118				; 00000076H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	mov	rax, QWORD PTR __security_cookie
	xor	rax, rbp
	mov	QWORD PTR __$ArrayPad$[rbp], rax
	lea	rcx, OFFSET FLAT:__201522C9_Main@cpp
	call	__CheckForDebuggerJustMyCode

; 13   : 	// Allocation on Stack
; 14   : 	int value = 5;

	mov	DWORD PTR value$[rbp], 5

; 15   : 	int array[5];
; 16   : 	array[0] = 1;

	mov	eax, 4
	imul	rax, rax, 0
	mov	DWORD PTR array$[rbp+rax], 1

; 17   : 	array[1] = 2;

	mov	eax, 4
	imul	rax, rax, 1
	mov	DWORD PTR array$[rbp+rax], 2

; 18   : 	array[2] = 3;

	mov	eax, 4
	imul	rax, rax, 2
	mov	DWORD PTR array$[rbp+rax], 3

; 19   : 	array[3] = 4;

	mov	eax, 4
	imul	rax, rax, 3
	mov	DWORD PTR array$[rbp+rax], 4

; 20   : 	array[4] = 5;

	mov	eax, 4
	imul	rax, rax, 4
	mov	DWORD PTR array$[rbp+rax], 5

; 21   : 	Vector3 vector;

	lea	rcx, QWORD PTR vector$[rbp]
	call	??0Vector3@@QEAA@XZ			; Vector3::Vector3

; 22   : 
; 23   : 	// Allocation on Heap
; 24   : 	int* hvalue = new int;

	mov	ecx, 4
	call	??2@YAPEAX_K@Z				; operator new
	mov	QWORD PTR $T5[rbp], rax
	mov	rax, QWORD PTR $T5[rbp]
	mov	QWORD PTR hvalue$[rbp], rax

; 25   : 	*hvalue = 5;

	mov	rax, QWORD PTR hvalue$[rbp]
	mov	DWORD PTR [rax], 5

; 26   : 	int* harray = new int[5];

	mov	ecx, 20
	call	??_U@YAPEAX_K@Z				; operator new[]
	mov	QWORD PTR $T6[rbp], rax
	mov	rax, QWORD PTR $T6[rbp]
	mov	QWORD PTR harray$[rbp], rax

; 27   : 	harray[0] = 1;

	mov	eax, 4
	imul	rax, rax, 0
	mov	rcx, QWORD PTR harray$[rbp]
	mov	DWORD PTR [rcx+rax], 1

; 28   : 	harray[1] = 2;

	mov	eax, 4
	imul	rax, rax, 1
	mov	rcx, QWORD PTR harray$[rbp]
	mov	DWORD PTR [rcx+rax], 2

; 29   : 	harray[2] = 3;

	mov	eax, 4
	imul	rax, rax, 2
	mov	rcx, QWORD PTR harray$[rbp]
	mov	DWORD PTR [rcx+rax], 3

; 30   : 	harray[3] = 4;

	mov	eax, 4
	imul	rax, rax, 3
	mov	rcx, QWORD PTR harray$[rbp]
	mov	DWORD PTR [rcx+rax], 4

; 31   : 	harray[4] = 5;

	mov	eax, 4
	imul	rax, rax, 4
	mov	rcx, QWORD PTR harray$[rbp]
	mov	DWORD PTR [rcx+rax], 5

; 32   : 	Vector3* hvector = new Vector3();

	mov	ecx, 12
	call	??2@YAPEAX_K@Z				; operator new
	mov	QWORD PTR $T8[rbp], rax
	cmp	QWORD PTR $T8[rbp], 0
	je	SHORT $LN3@main
	mov	rcx, QWORD PTR $T8[rbp]
	call	??0Vector3@@QEAA@XZ			; Vector3::Vector3
	mov	QWORD PTR tv138[rbp], rax
	jmp	SHORT $LN4@main
$LN3@main:
	mov	QWORD PTR tv138[rbp], 0
$LN4@main:
	mov	rax, QWORD PTR tv138[rbp]
	mov	QWORD PTR $T7[rbp], rax
	mov	rax, QWORD PTR $T7[rbp]
	mov	QWORD PTR hvector$[rbp], rax

; 33   : 
; 34   : 	delete hvalue;

	mov	rax, QWORD PTR hvalue$[rbp]
	mov	QWORD PTR $T9[rbp], rax
	mov	edx, 4
	mov	rcx, QWORD PTR $T9[rbp]
	call	??3@YAXPEAX_K@Z				; operator delete
	cmp	QWORD PTR $T9[rbp], 0
	jne	SHORT $LN5@main
	mov	QWORD PTR tv141[rbp], 0
	jmp	SHORT $LN6@main
$LN5@main:
	mov	QWORD PTR hvalue$[rbp], 33059		; 00008123H
	mov	rax, QWORD PTR hvalue$[rbp]
	mov	QWORD PTR tv141[rbp], rax
$LN6@main:

; 35   : 	delete[] harray;

	mov	rax, QWORD PTR harray$[rbp]
	mov	QWORD PTR $T10[rbp], rax
	mov	rcx, QWORD PTR $T10[rbp]
	call	??_V@YAXPEAX@Z				; operator delete[]
	cmp	QWORD PTR $T10[rbp], 0
	jne	SHORT $LN7@main
	mov	QWORD PTR tv144[rbp], 0
	jmp	SHORT $LN8@main
$LN7@main:
	mov	QWORD PTR harray$[rbp], 33059		; 00008123H
	mov	rax, QWORD PTR harray$[rbp]
	mov	QWORD PTR tv144[rbp], rax
$LN8@main:

; 36   : 	delete hvector;

	mov	rax, QWORD PTR hvector$[rbp]
	mov	QWORD PTR $T11[rbp], rax
	mov	edx, 12
	mov	rcx, QWORD PTR $T11[rbp]
	call	??3@YAXPEAX_K@Z				; operator delete
	cmp	QWORD PTR $T11[rbp], 0
	jne	SHORT $LN9@main
	mov	QWORD PTR tv148[rbp], 0
	jmp	SHORT $LN10@main
$LN9@main:
	mov	QWORD PTR hvector$[rbp], 33059		; 00008123H
	mov	rax, QWORD PTR hvector$[rbp]
	mov	QWORD PTR tv148[rbp], rax
$LN10@main:

; 37   : 
; 38   : 	std::cin.get();

	mov	rcx, QWORD PTR __imp_?cin@std@@3V?$basic_istream@DU?$char_traits@D@std@@@1@A
	call	QWORD PTR __imp_?get@?$basic_istream@DU?$char_traits@D@std@@@std@@QEAAHXZ

; 39   : }

	xor	eax, eax
	mov	edi, eax
	lea	rcx, QWORD PTR [rbp-32]
	lea	rdx, OFFSET FLAT:main$rtcFrameData
	call	_RTC_CheckStackVars
	mov	eax, edi
	mov	rcx, QWORD PTR __$ArrayPad$[rbp]
	xor	rcx, rbp
	call	__security_check_cookie
	lea	rsp, QWORD PTR [rbp+664]
	pop	rdi
	pop	rbp
	ret	0
main	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT text$x
text$x	SEGMENT
value$ = 4
array$ = 40
vector$ = 88
hvalue$ = 136
harray$ = 168
hvector$ = 200
$T5 = 424
$T6 = 456
$T7 = 488
$T8 = 520
$T9 = 552
$T10 = 584
$T11 = 616
tv148 = 632
tv144 = 632
tv141 = 632
tv138 = 632
__$ArrayPad$ = 640
main$dtor$0 PROC
	mov	QWORD PTR [rsp+8], rcx
	mov	QWORD PTR [rsp+16], rdx
	push	rbp
	push	rdi
	sub	rsp, 40					; 00000028H
	lea	rbp, QWORD PTR [rdx+32]
	mov	edx, 12
	mov	rcx, QWORD PTR $T8[rbp]
	call	??3@YAXPEAX_K@Z				; operator delete
	add	rsp, 40					; 00000028H
	pop	rdi
	pop	rbp
	ret	0
main$dtor$0 ENDP
text$x	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File C:\Users\binyi\source\repos\cpp_StackHeap\cpp_StackHeap\Main.cpp
;	COMDAT ??0Vector3@@QEAA@XZ
_TEXT	SEGMENT
this$ = 224
??0Vector3@@QEAA@XZ PROC				; Vector3::Vector3, COMDAT

; 7    : 	Vector3()

$LN3:
	mov	QWORD PTR [rsp+8], rcx
	push	rbp
	push	rdi
	sub	rsp, 232				; 000000e8H
	lea	rbp, QWORD PTR [rsp+32]
	lea	rcx, OFFSET FLAT:__201522C9_Main@cpp
	call	__CheckForDebuggerJustMyCode

; 8    : 		: a(10), b(20), c(30) {}

	mov	rax, QWORD PTR this$[rbp]
	mov	DWORD PTR [rax], 10
	mov	rax, QWORD PTR this$[rbp]
	mov	DWORD PTR [rax+4], 20
	mov	rax, QWORD PTR this$[rbp]
	mov	DWORD PTR [rax+8], 30
	mov	rax, QWORD PTR this$[rbp]
	lea	rsp, QWORD PTR [rbp+200]
	pop	rdi
	pop	rbp
	ret	0
??0Vector3@@QEAA@XZ ENDP				; Vector3::Vector3
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File C:\Users\binyi\source\repos\cpp_StackHeap\cpp_StackHeap\Main.cpp
;	COMDAT ?__empty_global_delete@@YAXPEAX_K@Z
_TEXT	SEGMENT
__formal$ = 224
__formal$ = 232
?__empty_global_delete@@YAXPEAX_K@Z PROC		; __empty_global_delete, COMDAT

$LN3:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	push	rbp
	push	rdi
	sub	rsp, 232				; 000000e8H
	lea	rbp, QWORD PTR [rsp+32]
	lea	rcx, OFFSET FLAT:__201522C9_Main@cpp
	call	__CheckForDebuggerJustMyCode
	lea	rsp, QWORD PTR [rbp+200]
	pop	rdi
	pop	rbp
	ret	0
?__empty_global_delete@@YAXPEAX_K@Z ENDP		; __empty_global_delete
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File C:\Users\binyi\source\repos\cpp_StackHeap\cpp_StackHeap\Main.cpp
;	COMDAT ?__empty_global_delete@@YAXPEAX@Z
_TEXT	SEGMENT
__formal$ = 224
?__empty_global_delete@@YAXPEAX@Z PROC			; __empty_global_delete, COMDAT

$LN3:
	mov	QWORD PTR [rsp+8], rcx
	push	rbp
	push	rdi
	sub	rsp, 232				; 000000e8H
	lea	rbp, QWORD PTR [rsp+32]
	lea	rcx, OFFSET FLAT:__201522C9_Main@cpp
	call	__CheckForDebuggerJustMyCode
	lea	rsp, QWORD PTR [rbp+200]
	pop	rdi
	pop	rbp
	ret	0
?__empty_global_delete@@YAXPEAX@Z ENDP			; __empty_global_delete
_TEXT	ENDS
END
